
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '&)\xc9\tK\xb0\xd8\xd3V0\xa4\xdbD\xbb\xbb\xc4'
    
_lr_action_items = {'ID':([2,4,],[3,6,]),'LBRACE':([3,],[4,]),'CLASS':([0,],[2,]),'RBRACE':([5,6,],[7,-2,]),'$end':([1,7,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'classdef':([4,],[5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> CLASS ID LBRACE classdef RBRACE','program',5,'p_program','langyacc.py',7),
  ('classdef -> ID','classdef',1,'p_classdef','langyacc.py',10),
]
